%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(echo_pb).
-define(echo_pb, true).

-define(echo_pb_gpb_version, "4.10.0").

-ifndef('HEARTBEATREQ_PB_H').
-define('HEARTBEATREQ_PB_H', true).
-record('HeartBeatReq',
        {
        }).
-endif.

-ifndef('HEARTBEATRESP_PB_H').
-define('HEARTBEATRESP_PB_H', true).
-record('HeartBeatResp',
        {now_ms                 :: non_neg_integer() % = 1, 32 bits
        }).
-endif.

-endif.
